src/ngx_http_mruby_module.c
raise method error code
```
location /mruby {
mruby_content_handler_code 'Nginx.echoo "aaa"';
}
```
```
ab -c 100 -n 100000 -k http://127.0.0.1:8001/mruby
```
```
matsumo+ 28223  0.0  0.0  27296  1688 ?        Ss   14:30   0:00 ./build/nginx/sbin/nginx
```
1688
```
matsumo+  2718 49.6  2.1 203376 177316 ?       Ss   14:41   0:11 ./build/nginx/sbin/nginx
```
1688 -> 177316
```
matsumo+ 28223 11.2  0.0  28528  3452 ?        Ss   14:30   0:11 ./build/nginx/sbin/nginx
```
1688 -> 3452
wow!
=> Fix memory leak when ngx_mruby raise error and return 5xx status code

src/ngx_http_mruby_module.c
```
location /mruby_full_obj {
mruby_set_code $matsu '"hogehoge"';
mruby_content_handler_code 'r = Nginx::Request.new; Nginx.echo r.var.matsu';
}
```
```
ab -c 100 -n 100000 -k http://127.0.0.1:8001/mruby_full_obj
```
```
matsumo+ 12217  0.0  0.0  27296  2164 ?        Ss   17:53   0:00 ./build/nginx/sbin/nginx
```
2164
```
matsumo+ 19054 37.2  0.2  47176 21776 ?        Ss   18:02   0:08 ./build/nginx/sbin/nginx
```
2164 ->
```
matsumo+ 12217 13.2  0.0  28360  3352 ?        Ss   17:53   0:08 ./build/nginx/sbin/nginx
```
2164 -> 3352
yey!
=> Fix memory leak when using mruby_set{,_code} directive

build.sh
`getconf _NPROCESSORS_ONLN` が 1 の時にビルドが失敗する問題を修正しました。
expr の結果が 0 のとき、return code が !0 になることがあります。`build.sh` では `set -e` としているため、それが異常コードと判定され実行に失敗していました。
=> Fix expr return value is 0

src/ngx_http_mruby_request.c, test/conf/nginx.conf, test/t/ngx_mruby.rb
This allows ngx_mruby to add new incoming headers, and delete incoming and outgoing headers. This is a useful feature that lua-nginx has, allowing ngx_mruby to act as a middleware to change headers to and from a proxy server.
```nginx
server {
listen      8001;
server_name localhost;
location / {
mruby_content_handler_code '
r = Nginx::Request.new
Nginx.echo "Incoming headers:"
r.headers_in.all.each do |key,val|
Nginx.echo "#{key}: #{val}"
end
';
}
}
```
```nginx
server {
listen      8000;
server_name localhost;
location / {
mruby_access_handler_code '
r = Nginx::Request.new
r.headers_in["x-new-header"] = "hoge"
r.headers_in.delete("X-Bad-Header")
';
proxy_pass http://localhost:8001;
}
}
```
```bash
$ curl -H "X-Bad-Header:asdf" "http://localhost:8001"
Incoming headers:
User-Agent: …
```
=> Allow deleting headers, creating new incoming headers

src/ngx_http_mruby_filter.c, src/ngx_http_mruby_module.c, test.sh, test/conf/nginx.conf, test/html/output_filter_header/index.html, test/t/ngx_mruby.rb
ngx_mruby can't control response headers at output_filter phase. So, this PR support the header control.
```nginx
location /hoge {
mruby_output_filter_code '
r = Nginx::Request.new
r.headers_out["Server2"] = "matsu"
';
}   
```
```
$ curl  http://127.0.0.1:58080/hoge/hello.html -v
* About to connect() to 127.0.0.1 port 58080 (#0)
*   Trying 127.0.0.1... connected
* Connected to 127.0.0.1 (127.0.0.1) port 58080 (#0)
> GET /hoge/hello.html HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: 127.0.0.1:58080
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.7.11
< Date: Wed, 10 Jun 2015 14:05:37 GMT
< Content-Type: text/html
< Content-Length: 6
< Last-Modified: Wed, 10 Jun 2015 12:28:00 GMT
< …
```
=> Support controling response headers at output_filter phase

src/ngx_http_mruby_request.c
- server start
```
sh test.sh
```
and
```
./build/nginx/sbin/nginx
```
- access client
```
while [ 1 ]; do curl http://127.0.0.1:58080/output_filter_header/index.html -v;done
```
sometimes curl wait header response. After this PR, fix this issue.
=> Fix bug; sometimes headers line include dust char

config, src/ngx_http_mruby_core.c, src/ngx_http_mruby_init.c, src/ngx_http_mruby_module.h, src/ngx_http_mruby_upstream.c, src/ngx_http_mruby_upstream.h, test/build_config.rb, test/conf/nginx.conf, test/t/ngx_mruby.rb
Add upstream class and methods. After merging this pull-request, ngx_mruby can setup upstream keepalive configuration per upstream host in Ruby code.
```nginx
location /upstream-keepalive {
mruby_set_code $backend '
u = Nginx::Upstreame.new "127.0.0.1:58081"
u.keepalive = true
u.keepalive_cache = 32
u.hostname
';
proxy_pass  http://$backend/keepalive;
}
```
=> Add Nginx::Upstream class and method

src/ngx_http_mruby_var.c, test/conf/nginx.conf, test/t/ngx_mruby.rb
`Var#exist?(var_name)` returns true when the nginx variable is found, otherwise it returns false.
`Var#method_missing` returns nil if the variable doesn't exist or is not found and it also logs an error like `ngx_mruby ERROR ngx_mrb_var_get:57: arg_foo not found`. I would like to check whether the variable exists for suppressing such an error log.
```ruby
r = Nginx::Request.new
Nginx.echo "foo: #{r.var.arg_foo}" if r.var.exist?("arg_foo")
```
=> Implement Var#exist?

src/ngx_http_mruby_var.c
This is related to #129 
Because nginx variable "not found" error is too verbose, just return nil without the error.
=> Suppress variable not found error because it is too verbose.

src/ngx_http_mruby_module.c, test/conf/nginx.conf
`mruby_set` directive ignore cache option.
```
mruby_set $hoge hoge.rb cache
```
After starting nginx with above configuration, nginx also changes response if changing `hoge.rb`.
=> Fix bug; mruby_set ignore "cache" option

src/ngx_http_mruby_var.c
ref: #130 
ngx_mruby sometimes missing nginx variable because of collecting mruby object as garbage. So, ngx_mruby allocate memory area for string object.
=> Fix bug; sometimes missing nginx variable

src/ngx_http_mruby_core.c, src/ngx_http_mruby_request.c, src/ngx_http_mruby_var.c, test.sh
=> Allocate memory for mruby object instead of the ptr of mruby object

.clang-format, src/ngx_http_mruby_request.c, test/conf/nginx.conf, test/t/ngx_mruby.rb
- config
```nginx
location /multi_headers_out {
mruby_content_handler_code '
r = Nginx::Request.new
r.headers_out["hoge"] = "dummy"
r.headers_out["hoge"] = %w(foo fuga)
Nginx.rputs r.headers_out["hoge"]
Nginx.return 200
';
}
location /multi_headers_in {
mruby_content_handler_code '
r = Nginx::Request.new
r.headers_in["hoge"] = [r.headers_in["hoge"], "fuga"]
Nginx.rputs r.headers_in["hoge"]
Nginx.return 200
';
}
```
- curl
```
$ curl -v http://127.0.0.1:58080/multi_headers_out
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 58080 (#0)
> GET /multi_headers_out HTTP/1.1
> Host: 127.0.0.1:58080
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Fri, 02 Oct 2015 07:32:53 GMT
< Content-Length: 15
< Connection: keep-alive
< Server: global_ngx_mruby
< hoge: …
```
=> Support multipul headers

src/stream/ngx_stream_mruby_connection.c, src/stream/ngx_stream_mruby_connection.h, src/stream/ngx_stream_mruby_core.c, src/stream/ngx_stream_mruby_module.c, src/stream/ngx_stream_mruby_module.h, test/conf/nginx.stream.conf
- `nginx.conf`
```nginx
stream {
upstream dynamic_server0 {
server 127.0.0.1:58080;
}
upstream dynamic_server1 {
server 127.0.0.1:58081;
}
mruby_stream_init_code '
Userdata.new.new_upstream = "127.0.0.1:58081"
';
mruby_stream_init_worker_code '
p "ngx_mruby: STREAM: mruby_stream_init_worker_code"
';
mruby_stream_exit_worker_code '
p "ngx_mruby: STREAM: mruby_stream_exit_worker_code"
';
server {
listen 12346;
mruby_stream_code '
Nginx::Stream::Connection.new("dynamic_server0").upstream_server = Userdata.new.new_upstream
';
proxy_pass dynamic_server0;
}
server {
listen 12345;
mruby_stream build/nginx/html/stream_lb.rb;
proxy_pass dynamic_server1;
}
server {
listen 12347;
mruby_stream_code '
if Nginx::Stream::Connection.remote_ip == "127.0.0.1"
current_status = …
```
=> Support stream init and exit directives with mruby, and access control methods

.travis.yml, Makefile.in, config, src/http/ngx_http_mruby_init.c, src/http/ngx_http_mruby_module.c, src/http/ngx_http_mruby_module.h, src/http/ngx_http_mruby_ssl.c, src/http/ngx_http_mruby_ssl.h, src/stream/ngx_stream_mruby_connection.c, test.sh, test/build_config.rb, test/conf/nginx.conf, test/t/ngx_mruby.rb
- config
```nginx
server {
listen       58082 ssl;
server_name  localhost;
ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers         HIGH:!aNULL:!MD5;
ssl_certificate     /Users/matsumoto_r/DEV/ngx_mruby/build/nginx/html//dummy.crt;
ssl_certificate_key /Users/matsumoto_r/DEV/ngx_mruby/build/nginx/html//dummy.key;
mruby_ssl_handshake_handler_code '
ssl = Nginx::SSL.new
ssl.certificate = "/Users/matsumoto_r/DEV/ngx_mruby/build/nginx/html//server.crt"
ssl.certificate_key = "/Users/matsumoto_r/DEV/ngx_mruby/build/nginx/html//server.key"
';
location / {
mruby_content_handler_code "Nginx.rputs 'ssl test ok'";
}
}
```
- normal ssl
```nginx
server {
listen       58082 ssl;
server_name  localhost;
ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers         HIGH:!aNULL:!MD5;
ssl_certificate …
```
=> Support ssl_handshake handler and dynamic certificate change

src/http/ngx_http_mruby_module.c, test/t/ngx_mruby.rb
return tls handshake error when dynamic cert read was failed.
- command line
```
$  openssl s_client -servername matsumotory.foo -connect 127.0.0.1:58082 < /dev/null 2> /dev/null
CONNECTED(00000003)
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 342 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
Protocol  : TLSv1.2
Cipher    : 0000
Session-ID:
Session-ID-ctx:
Master-Key:
Key-Arg   : None
PSK identity: None
PSK identity hint: None
SRP username: None
Start Time: 1452851801
Timeout   : 300 (sec)
Verify return code: 0 (ok)
---
```
- error log
```
2016/01/15 19:01:47 [debug] 58613#0: *1 ngx_mruby : mruby ssl handler: …
```
=> Add dynamic certificate read error

Makefile.in
Git repository of nginx has no `configure` script in top of directory. It location is under `auto` directory.
This changes make to work develop version of NGINX.
=> Support development version of NGINX

mrbgems/ngx_mruby_mrblib/mrblib/mrb_nginx.rb, test/conf/nginx.conf, test/t/ngx_mruby.rb
I added `get_uri_args`, `set_uri_args` and `get_post_args`. We need to convert String to Hash using args parameter in Nginx::Request. This pull request makes to easy to use it.
These are stolen from ngx_lua :octocat:
=> Added helper method for Nginx::Request instance

build.sh
In the case where you use `ln of GNU coreutils (ver. 8.22)`,
if you want to replace an existing directory symlink, you should add this option.
> This time, I wanted to overwrite other nginx version.
- GNU Manual says
```
-n, --no-dereference
treat LINK_NAME as a normal file if it is a symbolic link
to a directory
```
I checked `ln of FreeBSD 10.3`
- FreeBDS Manual say
```
-h	   If the target_file or target_dir is a symbolic link,	do not follow
it.	This is	most useful with the -f	option,	to replace a symlink
which may point to a	directory.
...
-n	   Same	as -h, for compatibility with other ln implementations.
```
It seems that `each ln command` can use this option.
but I couldn't check `ln of other platform`.
=> FIX: Add ln option "-n"

test/t/ngx_mruby.rb
body_filterをかけた後、content-lengthヘッダと矛盾がないかを見るようにします。
進行中の #172 がうまく行ったら通る、というつもりです。
=> Update testcase: check content-length for body_filter

mrbgems/rack-based-api/mrblib/rack.rb, test/conf/nginx.conf, test/t/ngx_mruby.rb
The change requires mattn/mruby-json@f7f0ed91de172cdf9e4ad485b4a4cb29f0da542a to pass the test.
=> Add rack.logger support.

src/http/ngx_http_mruby_module.c, src/stream/ngx_stream_mruby_module.c
Thanks @hiboma and @hsbt for the report.
```
$ sudo cat /etc/nginx/nginx.conf
user  nginx;
daemon off;
worker_processes 1;
events { worker_connections 1024; }
http {}
```
```
sudo /usr/sbin/nginx 
```
```
$  while [ 1 ]; do sudo /usr/sbin/nginx -s reload; ps auxf | grep '[n]ginx: master'; sleep 1; done;
root      4147  0.0  0.9  54152  4792 pts/1    S+   14:34   0:00  |               \_ nginx: master process /usr/sbin/nginx
root      4147  0.0  1.0  54688  5332 pts/1    S+   14:34   0:00  |               \_ nginx: master process /usr/sbin/nginx
root      4147  0.0  1.1  55216  5856 pts/1    S+   14:34   0:00  |               \_ nginx: master process /usr/sbin/nginx
root      4147  0.2  1.2  55760  6376 pts/1    S+   14:34   0:00  |               \_ nginx: master process /usr/sbin/nginx …
```
=> Fix master process memory leak when reloading nginx

src/http/ngx_http_mruby_module.c
mruby_set with a non-existent file path give me the follwoing incorrect error message.
'mrb_file($foo)' should be 'mrb_file(/path/to/foo.rb).
```
nginx: [emerg] mrb_file($foo) open failed in /home/vagrant/ngx_mruby/build/nginx/conf/nginx.conf:89
```
Here is my configuration.
```
location /foo {
mruby_set $foo /path/to/foo.rb;
}
```
The change fixes the message as below:
```
nginx: [emerg] mrb_file(/path/to/foo.rb) open failed in /home/vagrant/ngx_mruby/build/nginx/conf/nginx.conf:89
```
=> Fix incorrect error messages.

build.sh
ngx_mruby has used git-subtree instead of git-submodule.
=> Remove git-submodule process on build.sh

test.sh
Apply 453325ac3b760481eca5d7d849e6e1f89be4a0a5 to test.sh.
=> Don't use git submodule command at build time.

src/http/ngx_http_mruby_core.c, test/conf/nginx.conf, test/t/ngx_mruby.rb
ref: http://buty4649.hatenablog.com/entry/2016/07/31/235836 [JA]
use like the following example:
```nginx
mruby_set_code $is_iphone '
Nginx::FALSE
';
if($is_iphone) {
}
```
=> Support nginx bool value

mruby_test/build_config.rb, src/http/ngx_http_mruby_module.c, src/http/ngx_http_mruby_module.h, test.sh, test/build_config.rb, test/conf/nginx.conf, test/html/set_ssl_cert_and_key.rb, test/t/ngx_mruby.rb
This function is equivalent to mruby_ssl_handshake_handler_code() #145, except that the file specified by ngx_mruby-script contains the mruby code to be executed.
=> Implement mruby_ssl_handshake_handler()

mrbgems/rack-based-api/mrblib/rack.rb, test/t/ngx_mruby.rb
Add CONTENT_TYPE and CONTENT_LENGTH to Rack environment to comply with Rack spec.
The spec doesn't allow the env contains HTTP_CONTENT_TYPE or HTTP_CONTENT_LENGTH,
but I keep them for backward compatibilty.
=> Add CONTENT_TYPE and CONTENT_LENGTH to Rack environment

mrbgems/rack-based-api/mrblib/rack.rb, test/conf/nginx.conf, test/t/ngx_mruby.rb
ngx_mruby doesn't complain if Rack response headers is an Array of Hash, but it causes segmentation fault.
```
location /foo {
mruby_content_handler_code '
class Foo
def call(env)
[200, [{"X-Foo" => "foo"}], ["body"]]
end
end
run Foo.new
';
}
```
```
Program received signal SIGSEGV, Segmentation fault.
ngx_mrb_set_request_header (mrb=mrb@entry=0x845190, headers=headers@entry=0xa709b0, pool=0xa70790, mrb_key=..., mrb_val=..., 
update=update@entry=1) at /home/vagrant/mon/ngx_mruby/src/http/ngx_http_mruby_request.c:312
312	  key_len = (size_t)RSTRING_LEN(mrb_key);
Missing separate debuginfos, use: debuginfo-install glibc-2.17-106.el7_2.6.x86_64 libgcc-4.8.5-4.el7.x86_64 libstdc++-4.8.5-4.el7.x86_64 nss-softokn-freebl-3.16.2.3-13.el7_1.x86_64 openssl-libs-1.0.1e-51.el7_2.5.x86_64 …
```
=> Check response header type more strictly to avoid segmentation fault.

src/http/ngx_http_mruby_module.c, test/conf/nginx.conf, test/html/issue-210.rb, test/t/ngx_mruby.rb
=> Don't allow post_read directives on location context

test.sh
In nginx 1.11.5, it can omit --without-stream_access_module option from test.sh.
And if it's ok with you, I'll update wiki https://github.com/matsumoto-r/ngx_mruby/wiki/Install#if-you-use-ngx_mruby-stream-module .
=> In nginx 1.11.5, it can omit --without-stream_access_module option from test.sh

src/http/ngx_http_mruby_module.h
There are some features (F_OK, access()) in
src/http/ngx_http_mruby_module.c which requires <io.h> to build on MinGW
=> Fix missing io header file to build on MinGW

src/http/ngx_http_mruby_core.c, src/http/ngx_http_mruby_ssl.c, src/stream/ngx_stream_mruby_core.c
* Use MRB_ARGS_REQ(2) instead of MRB_ARGS_ANY() because log methods require only a loglevel and a message.
* Use [mrb_obj_as_string](https://github.com/mruby/mruby/blob/1.2.0/src/string.c#L1668-L1680) function to convert an object to Ruby string.
=> Refactor log(errlogger) methods in ngx_mruby

Makefile.in
because config has been generated from config.in since b26b663.
=> Run `make clean` or `make clobber`, remove config

build_config.rb
Remove matsumotory/mruby-ngx-mruby-ext.
It is merged to matsumotory/ngx_mruby in 2014.
=> Remove matsumotory/mruby-ngx-mruby-ext.

src/stream/ngx_stream_mruby_connection.c, test/conf/nginx.stream.conf, test/t/ngx_mruby.rb
Add the following methods for ip and port of stream module:
- `Nginx::Stream::Connection#{local_ip,local_ip_port,local_port,remote_port}`
- `Nginx::Stream::Connection.{local_ip,local_ip_port,local_port,remote_port}`
=> Add stream ip and port methods

mrbgems/rack-based-api/mrblib/rack.rb
If I remove `iij/mruby-io` from build_config.rb, it raise NameError.
```
ngx_mruby/mrbgems/rack-based-api/mrblib/rack.rb:51: undefined method 'gets' for class 'Kernel::Rack::LazyStringIO' (NameError)
```
I think `iij/mruby-io` is optional mgem.
I hope to remove dependency to mruby-io.
Sorry, I don't know how to test of this gem.
=> Remove dependency to mruby-io

src/http/ngx_http_mruby_module.c, test/conf/nginx.conf, test/t/ngx_mruby.rb
When there is access from clients not compatible with SNI, mruby_script can be executed on IP basis
=> support to ip base TLS handshake

src/http/ngx_http_mruby_module.c
I fixed a similar bug in b9584cab78688f922ab5d7d0f0c9a50e8794b848.
=> Fix segfault if code is not cached and rewritten with a syntax error during run time

.travis.yml, src/http/ngx_http_mruby_module.c
* Don't ignore setting der_certificate failure.
* Cat error log on travis if build failed. It makes debug easier.
=> Improve ssl error handling

Makefile.in, build.sh, build_config.rb, configure, configure.in, test.sh, test/t/ngx_mruby.rb
Get rid of a few environment variable in Makefile. build.sh and test.sh still respect them.
* NGX_OPENSSL_SRC and NGX_OPENSSL_OPT are retired from Makefile.
* BUILD_DYNAMIC_MODULE is almost gone from Makefile. Instead add --enable-dynamic-module support to configure.
* build_config.rb and test/t/ngx_mruby.rb don't use BUILD_DYNAMIC_MODULE anymore.
* Add --with-build-dir support to configure.
=> Simplify Makefile.

.travis.yml, src/http/ngx_http_mruby_core.c, src/http/ngx_http_mruby_core.h, src/http/ngx_http_mruby_module.c, test.sh, test/conf/nginx.conf, test/html/backtrace.rb, test/t/ngx_mruby.rb
If you build ngx_mruby with NGX_DEBUG, you will get exception stack trace as below.
```
2017/05/16 03:58:05 [error] 5032#0: *114 mrb_run failed: return 500 HTTP status code to client: error: build/nginx/html/backtrace.
rb:10: Intentional Error for testing ngx_mrb_log_backtrace (RuntimeError), client: 127.0.0.1, server: localhost, request: "GET /ba
cktrace HTTP/1.0", host: "127.0.0.1"
2017/05/16 03:58:05 [error] 5032#0: *114 build/nginx/html/backtrace.rb:10:in Bar.bar, client: 127.0.0.1, server: localhost, reques
t: "GET /backtrace HTTP/1.0", host: "127.0.0.1"
2017/05/16 03:58:05 [error] 5032#0: *114 build/nginx/html/backtrace.rb:4:in Foo.foo, client: 127.0.0.1, server: localhost, request
: "GET /backtrace HTTP/1.0", host: "127.0.0.1"
2017/05/16 03:58:05 [error] 5032#0: *114 …
```
=> exception stack trace log support

src/http/ngx_http_mruby_core.c
=> ngx_mrb_log_backtrace only defined using NGX_DEBUG

src/stream/ngx_stream_mruby_core.c, src/stream/ngx_stream_mruby_module.c, src/stream/ngx_stream_mruby_module.h, test/conf/nginx.stream.conf, test/t/ngx_mruby.rb
```nginx
server {
mruby_stream_server_context_code '
Nginx::Stream.add_listener({address: "127.0.0.1:12350"})
Nginx::Stream.add_listener({address: "12351"})
';
proxy_pass static_server0;
}
```
=> Support stream listener method on server context

src/http/ngx_http_mruby_module.c
ngx_mruby sometimes fails to read request body.  The change fixes it.
I have reproducible code that I can't make open.  I tried to write small reproducible code, but it doesn't work.
=> Don't give up reqding request body.

docs/README.md
ドキュメントのリンク先がデッドリンクになっていたので修正しました。
ドキュメントの体裁の修正のためチェックリストは削除しています。
=> fix deadlink in document

build_config.rb
~~- [ ] Add patches into `src/`.~~
~~- [ ] Add test into `test/`. Please see about [test docs](https://github.com/matsumotory/ngx_mruby/tree/master/docs/test).~~
~~- [ ] Add docs into `docs/` if you change the features such as [build system](https://github.com/matsumotory/ngx_mruby/tree/master/docs/install), [Ruby methods, class](https://github.com/matsumotory/ngx_mruby/tree/master/docs/class_and_method) and [nginx directives](https://github.com/matsumotory/ngx_mruby/tree/master/docs/directives).~~
This PR doesn't contain modifying both implementation and test.
In my mac PC, mruby build is failed caused by including `auto-ssl` mrbgems. I want a convenient parameter to fix it.
I've installed openssl by using homebrew, so I give the include path:
```
$ …
```
=> Enable to specify LDFLAGS via environment variables

src/http/ngx_http_mruby_upstream.c, src/http/ngx_http_mruby_var.c
mrb_get_args() with format specifier "i" and "*" requires mrb_int. It is now 64 bit on 64 bit systems.
Using 32 bit int might cause buffer overflows with the latest mruby.
See https://github.com/mruby/mruby/commit/f0f4a1088a270e339407a24ffe8be748f4764fc2
I found it by inspection, so I don't know if it actually happens.
=> Use mrb_int to avoid possible buffer overflows.

docs/install/README.md
build_config_dynamic.rb was integrated into build_config.rb, so we need to pass `--enable-dynamic-module` to `configure` script instead of directly set `-fPIC` flag.
=> Fix description about already integrated build_config_dynamic.rb

mrbgems/ngx_mruby_mrblib/mrblib/mrb_nginx.rb, test/conf/nginx.conf, test/t/ngx_mruby.rb
When interpreting the parameters which value side was empty, it had been caused an exception.
```
> args_to_hash("a=1&b=2&c=&d=4")
ArgumentError: odd number of arguments for Hash
```
this pull request changes that empty value parse it as an empty string.
```
> args_to_hash("a=1&b=2&c=&d=4")
=> {"a"=>"1", "b"=>"2", "c"=>"", "d"=>"4"}
```
=> Avoid odd number exception / `Nginx.Request#args_to_hash (mrblib)`

src/http/ngx_http_mruby_core.c, src/http/ngx_http_mruby_module.c, src/http/ngx_http_mruby_request.c, src/http/ngx_http_mruby_upstream.c, src/stream/ngx_stream_mruby_connection.c, src/stream/ngx_stream_mruby_module.c
It seems there are some changes by updating clang version.
the PR run `apply-clang-format` in `6.0.0`.
Also, we have a way setting some parameter to `.clang-format`.
Which would you prefer?
=> run apply-clang-format, clang-format version 6.0.0

build_config.rb
They are part of mruby distribution now. See ngx_mruby/mruby/mrbgems.
=> Remove iij/mruby-io, iij/mruby-pack, and iij/mruby-socket.

src/stream/ngx_stream_mruby_module.c
This change fixes the following memory leak.
```
==25107== 84 (72 direct, 12 indirect) bytes in 1 blocks are definitely lost in loss record 72 of 142
==25107==    at 0x4C29BFD: malloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==25107==    by 0x4C2BACB: realloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==25107==    by 0x56A206: mrb_default_allocf (state.c:55)
==25107==    by 0x56ABEE: mrb_realloc_simple (gc.c:206)
==25107==    by 0x56AC70: mrb_realloc (gc.c:220)
==25107==    by 0x56AD45: mrb_malloc (gc.c:242)
==25107==    by 0x56ADC6: mrb_calloc (gc.c:260)
==25107==    by 0x5B0C77: mrbc_context_new (parse.y:5678)
==25107==    by 0x55BE38: ngx_stream_mruby_shared_state_compile (ngx_stream_mruby_module.c:384)
==25107==    by 0x55C6A6: …
```
=> Fix memory leak.

docs/class_and_method/README.md
- No changes
- No changes, no tests
----
ngx_mruby has `Nginx::SSL#certificate_data=` and `Nginx::SSL#certificate_key_data=` methods but not documented.
=> Update docs: Add certificate_data= and certificate_key_data=

build_config.rb, config.in, docs/class_and_method/README.md, mrbgems/ngx_mruby_mrblib/mrblib/mrb_nginx.rb, src/http/ngx_http_mruby_async.c, src/http/ngx_http_mruby_async.h, src/http/ngx_http_mruby_core.c, src/http/ngx_http_mruby_core.h, src/http/ngx_http_mruby_init.c, src/http/ngx_http_mruby_module.c, src/http/ngx_http_mruby_module.h, src/http/ngx_http_mruby_request.c, src/http/ngx_http_mruby_upstream.c, src/stream/ngx_stream_mruby_connection.c, src/stream/ngx_stream_mruby_module.c, test/conf/nginx.conf, test/t/ngx_mruby.rb
=> Run all request processing handler on fiber and support simple async methods

build_config.rb
it's related to the following commit: f104e4867e578b2192f1b951c302ba3c5901cce3
=> Remove iij/mruby-pack in test

src/http/ngx_http_mruby_async.c
v2-devにおいて高負荷時に `*** stack smashing detected ***: nginx: worker process terminated` のエラーログとともにwarkerが終了する不具合がありました。timerの値を受け取る型を変更することで症状の改善が認められたので対応しました。
=> fix stack smashing detected

dependence/ngx_devel_kit/src/ndk_set_var.c, src/http/ngx_http_mruby_async.c, src/http/ngx_http_mruby_core.c, src/http/ngx_http_mruby_core.h, src/http/ngx_http_mruby_module.c, src/http/ngx_http_mruby_module.h, src/http/ngx_http_mruby_request.c, src/http/ngx_http_mruby_upstream.c, src/http/ngx_http_mruby_var.c, src/http/ngx_http_mruby_var.h, src/stream/ngx_stream_mruby_connection.c, src/stream/ngx_stream_mruby_module.c, test/conf/nginx.conf, test/t/ngx_mruby.rb
Nginx::Async.sleep利用時に、rewrite_handlerから見るとmrubyのset_codeのrubyコードはsleepを待たずに終了して見えるため、後続の[ngx_http_script_set_var_code](https://github.com/phusion/nginx/blob/master/src/http/ngx_http_script.c#L1666)が空振り実行されてしまい、timer後のmrubyの戻り値が変数に設定されない問題がありました。
このPRでは設定する変数名をコンテキストに記憶しておき、timer後にその変数名に対してmrubyコードの戻り値を設定することで意図した動作になるように変更しています。
=> Support async setcode

src/http/ngx_http_mruby_async.c, src/http/ngx_http_mruby_core.c, src/http/ngx_http_mruby_core.h, src/http/ngx_http_mruby_filter.c, src/http/ngx_http_mruby_module.c
refs: https://github.com/matsumotory/ngx_mruby/issues/357
`ngx_http_mruby_ctx_t` がnull状態になる実装箇所があったため、 `ngx_mrb_http_get_module_ctx` メソッドを定義し、get時に値が無ければallocate + setする実装を追加しました。
=> fix #357 Create ngx_http_mruby_ctx_t if you do not have it

src/http/ngx_http_mruby_async.c, src/http/ngx_http_mruby_module.c
fiberがraiseした時でも `ngx_mrb_var_set_vector` を実行する分岐になっていたため、不正な値が渡ってくるバグが有りました。
=>  ngx_mrb_var_set_vector is not executed when fiber is raise

src/http/ngx_http_mruby_async.c, src/http/ngx_http_mruby_async.h, src/http/ngx_http_mruby_module.c
nginx_mruby v2のSSL handshake時にstack level too deepが発生するため、procオブジェクトの実行をmrb_funcallからmrb_runへ変更しました。 
```
2018/05/23 18:18:32 [debug] 3584#0: *39003 accept: 111.108.184.71:52759 fd:12
2018/05/23 18:18:32 [debug] 3584#0: *39003 event timer add: 12: 60000:13994782786
2018/05/23 18:18:32 [debug] 3584#0: *39003 reusable connection: 1
2018/05/23 18:18:32 [debug] 3584#0: *39003 epoll add event: fd:12 op:1 ev:80002001
2018/05/23 18:18:32 [debug] 3584#0: *39003 http check ssl handshake
2018/05/23 18:18:32 [debug] 3584#0: *39003 http recv(): 1
2018/05/23 18:18:32 [debug] 3584#0: *39003 https ssl handshake: 0x16
2018/05/23 18:18:32 [debug] 3584#0: *39003 tcp_nodelay
2018/05/23 18:18:32 [debug] 3584#0: *39003 SSL server name: "www.example.com"
2018/05/23 18:18:32 [debug] 3584#0: *39003 ngx_mruby : …
```
=> Execute the proc object with mrb_run

mrbgems/ngx_mruby_mrblib/mrblib/mrb_nginx.rb, src/http/ngx_http_mruby_async.c
There is a mruby specification that mruby does not cross the fiber boundary between C and Ruby. Since current implementation is an undefined behavior, so we need to rewrite it to appropriate behavior for the specification.
=> Fix cross fiber boundary problem between C and Ruby

.travis.yml, src/http/ngx_http_mruby_async.c, src/http/ngx_http_mruby_core.c, src/http/ngx_http_mruby_module.c, test/conf/nginx.conf, test/t/ngx_mruby.rb
ngx_mruby is waiting for a long time when ngx_mruby request other location which use proxy_pass using `sub_request` method.
=> Fix bug; don't run mruby body filter when read upstream buffer completely

src/http/ngx_http_mruby_async.c, src/http/ngx_http_mruby_module.c
ngx_mruby v2 leak object when using Nginx::Async class.
- nginx A
```nginx
worker_processes  1;
events {
worker_connections  1024;
}
daemon off;
master_process off;
error_log logs/error.log warn;
http {
include       mime.types;
server {
listen       48080;
server_name  localhost;
root /home/ubuntu/DEV/ngx_mruby/build/nginx/html/;
location /mruby {
mruby_rewrite_handler_code 'Nginx::Async.sleep 5; Nginx.echo "done"';
#mruby_rewrite_handler_code 'Nginx.echo "done"';
}
}
}
```
- nginx B
```nginx
worker_processes  1;
events {
worker_connections  1024;
}
daemon off;
master_process off;
error_log logs/error.log warn;
http {
include       mime.types;
server {
listen       58080;
server_name  localhost;
root /home/ubuntu/DEV/ngx_mruby/build/nginx/html/;
location /sub_req_proxy_pass {
proxy_pass …
```
=> Fix object leak using async class

src/http/ngx_http_mruby_async.c
Remove unused variable causing an error on some build system like dpkg-buildpackage.
=> Remove unused variable

docs/class_and_method/README.md, src/http/ngx_http_mruby_ssl.c, test/conf/nginx.conf, test/t/ngx_mruby.rb
hi! ry sann!
SSLハンドシェーク中にTLSのバージョンを取得できるようにしました。これによって古いクライアントからの接続要求時に処理を分岐するなどの実装が可能になります。
=> Support to get client tls version

Dockerfile
- The base Docker image is old, so I update it.
- Because, of the version of open-ssl even if you build nginx.conf containing SSL related configure, it will cause an error 
- Should we PR code that solves the openssl problem without update the base image version?
```
FROM matsumotory/ngx-mruby:latest
```
```
user daemon;
daemon off;
master_process off;
worker_processes auto;
error_log stderr;
events {
worker_connections 1024;
}
http {
include mime.types;
mruby_init_worker_code '
Userdata.new.redis = Redis.new "redis", 6379
';
server {
listen 80;
server_name _;
location / {
mruby_content_handler_code 'Nginx.rputs "hello #{Nginx::Request.new.hostname} world!"';
}
}
server {
listen 443 ssl;
server_name  _;
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers HIGH:!aNULL:!MD5;
ssl_certificate …
```
=> Base Docker Image Update Ubuntu 18.04

src/http/ngx_http_mruby_module.c
With -DNGX_MRUBY_IREP_DEBUG, you will see the following generated code information for debug.
```
00001 NODE_SCOPE:
00001   NODE_BEGIN:
00001     NODE_CALL(.):
00001       NODE_CONST Nginx
00001       method='return' (1460)
00001       args:
00001         NODE_COLON2:
00001           NODE_CONST Nginx
00001           ::OK
irep 0xfd9f90 nregs=4 nlocals=1 pools=0 syms=3 reps=0
file: INLINE CODE
1 000 OP_GETCONST	R1	:Nginx
1 003 OP_GETCONST	R2	:Nginx
1 006 OP_GETMCNST	R2	R2::OK
1 009 OP_SEND	R1	:return	1
1 013 OP_RETURN	R1		
1 015 OP_STOP
00002 NODE_SCOPE:
00002   NODE_BEGIN:
00002     NODE_CALL(.):
00002       NODE_CONST Nginx
00002       method='rputs' (1462)
00002       args:
00002         NODE_STR "OK" len 2
00003     NODE_CALL(.):
00003       NODE_CONST Nginx
00003       method='return' …
```
=> Print generated code for debug if NGX_MRUBY_IREP_DEBUG is defined.

mrbgems/ngx_mruby_mrblib/mrblib/mrb_nginx.rb, src/http/ngx_http_mruby_request.c, test/t/ngx_mruby.rb
* Remove temporary solution for https://github.com/iij/mruby-io/issues/75 that was fixed in Apr 2017.
* Move read_body to mrb_nginx.rb from ngx_http_mruby_request.c to reduce C code size. The method (in C, ngx_mrb_read_request_body) does nothing after #269.
=> Refactoring

docs/class_and_method/README.md
=> Fix broken merge in previous commit.

mrbgems/auto-ssl/mrblib/mrb_auto_ssl_client.rb
When running fast cert, you need to remove the key before retrying.
=> Clear private key when authentication failed

test.sh
I changed test.sh to use pkill instead of killall for CentOS. killall isn't installed by default.
=> Use pkill on CentOS. killall isn't installed by default.

update-devkit-subtree, update-mruby-subtree
"==" operator for test(1) command should not be used for POSIX conformance.
It is a extension feature of bash and other some shell.
=> Fix portability for sh script

.travis.yml, Makefile.in, Vagrantfile, misc/Dockerfile.travis_emulate, misc/provision.sh
This PR will be able to build the ngx_mruby with openssl-1.1.x.
- Support build with openssl-1.1.x (not supported build opt `enable-tlsext` in openssl-1.1 later)
- Some fixes to CI environment with built-in openssl
- Upgrade OS to ubuntu:bionic to use libssl-1.1
- Add environment variable `LD`, Required here: https://github.com/mruby/mruby/blob/b7af9c47b3f6ec656f7e2d7ee4c1d11cda667748/mrbgems/mruby-bin-mrbc/mrbgem.rake#L12
- Same modification to `Dockerfile.travis_emulate`
CI using openssl-1.0.x is gone.
I thought about doing both 1.0 and 1.1, but I thought it would be complicated.
Instead,
I performed a test overwriting this fix with 1.0.2. passed it.
https://github.com/takumakume/ngx_mruby/pull/1
=> Support build with openssl-1.1.x

src/stream/ngx_stream_mruby_async.c, src/stream/ngx_stream_mruby_async.h, src/stream/ngx_stream_mruby_module.c, src/stream/ngx_stream_mruby_module.h, test/conf/nginx.stream.conf, test/t/ngx_mruby.rb
Hi Mats!!!
Have you eaten dinner??
Nginx::Stream module is using `mrb->ud`.
it is a possibility of becoming a race condition when call Nginx::Stream::Async.sleep.
In this patch, added mrb-> ud consistency before and after run fiber.
Thanks!
=> Fix Nginx::Stream::Async race condition

docs/class_and_method/README.md
=> Fix link in document

.gitignore, Makefile.in, build.sh
* Remove mruby/build/* if mruby source is newer. Fix #448
* Don't remove mruby/build/* in build.sh. It is done by Makefile if necessary.
* Invoke rake with our own build_config.rb.
=> Fix #448 and minor build system issues

build.sh, src/http/ngx_http_mruby_core.c, src/http/ngx_http_mruby_module.c, src/http/ngx_http_mruby_module.h, src/stream/ngx_stream_mruby_core.c, src/stream/ngx_stream_mruby_core.h, test.sh
Fixed multiple definition errors with -fno-common. Fixed #451
=> Fixed multiple definition errors with -fno-common

Makefile.in
Add -I options only to CORE_LIBS to avoid generating strange compiler options like "-I -g -I -std=gnu99 -I -O3 -I -Wall".
=> Add -I options only to CORE_LIBS to fix #400.

build_config.rb
Hello,
I want to pass additional libraries to linker when building ngx_mruby module.
In my case, libfts, which seems to required with mruby_tempfile, was required to build ngx_mruby_module on Alpine Linux 3.10.
=> Pass additional libraries to linker via NGX_MRUBY_LIBS

.travis.yml, test.sh, test/t/ngx_mruby.rb
Introduce OpenSSLTestClient for making debug easier.
You can see output of openssl command if you run the test with DEBUG environment variable.
=> Refactoing openssl tests

Makefile.in
Fix #465 
ref: https://github.com/matsumotory/ngx_mruby/issues/465#issuecomment-643574920
=> mruby/ doesn't have /git by default because mruby/ was created by git subtree

src/http/ngx_http_mruby_request.c, test/conf/nginx.conf, test/t/ngx_mruby.rb
=> Fix Nginx::Headers_in[] returns wrong value. Fixed #471.

src/http/ngx_http_mruby_request.c, test/conf/nginx.conf, test/t/ngx_mruby.rb
Fix segmentation fault when set nil to Nginx::Headers_{in,out}. Fixed #473.
=> Fix segmentation fault when set nil to Nginx::Headers_{in,out}

index.html
fix document link on ngx_mruby gh_pages.
=> fix document link on ngx_mruby gh_pages.

src/http/ngx_http_mruby_async.h, src/http/ngx_http_mruby_connection.h, src/http/ngx_http_mruby_core.h, src/http/ngx_http_mruby_filter.h, src/http/ngx_http_mruby_init.h, src/http/ngx_http_mruby_request.h, src/http/ngx_http_mruby_server.h, src/http/ngx_http_mruby_ssl.h, src/http/ngx_http_mruby_upstream.h, src/http/ngx_http_mruby_var.h, src/stream/ngx_stream_mruby_async.h, src/stream/ngx_stream_mruby_connection.h, src/stream/ngx_stream_mruby_core.h, src/stream/ngx_stream_mruby_init.h, src/stream/ngx_stream_mruby_module.h
=> Add missing nginx headers to follow nginx's way. Fixed #495

misc/provision.sh
Fix error when provisioning Vagrant environment.
```
default: crypto/comp/c_zlib.c:35:11: fatal error: zlib.h: No such file or directory
default:  # include <zlib.h>
default:            ^~~~~~~~
default: compilation terminated.
```
=> Fix error when provisioning Vagrant environment

src/http/ngx_http_mruby_async.c, test/conf/nginx.conf, test/t/ngx_mruby.rb
Async.subrequestを利用する際に、すぐに503を返したいケースなどがあり、対応できていなかったので、Nginx::DECLINE、Nginx::OK以外のときは即レスポンスを返すようにします。
=> There are cases where I explicitly want to return 503.

src/http/ngx_http_mruby_async.c, test/conf/nginx.conf, test/t/ngx_mruby.rb
サブリクエストの実行時にも `mruby_set_code` で値を埋め込もうとしてしまっており、ファイバーの実行結果という意図しない値が設定されてしまう不具合があったので修正しました。1コミットめでテストが落ちて、2コミットめで通るようになってます。
=> When subrequest is used, set value is not used.

src/http/ngx_http_mruby_module.c
Fix: https://github.com/matsumotory/ngx_mruby/issues/508
In the code for http_mruby_module, header_filter return `NGX_ERROR` when other filters don't return `NGX_OK`.
If filters that return `NGX_AGAIN`, such as HTTP2 module,  it will not be processed correctly.
=> Fix http_mruby_module return statement

src/http/ngx_http_mruby_async.c, test/conf/nginx.conf, test/t/ngx_mruby.rb
sub requestのあとは明示的に `ngx_http_run_posted_requests` を呼び出して他のイベントをコールしないと行けないと思っていたのだがそんなことはなかったので、呼び出すをやめました。
元々顕在化した事象は、mrubyでrewrite handlerを使いつつ、nginxでもrewriteしているときにfinalizerが多重に呼ばれてセグフォするという問題が起きてそれで気づきました。なお、1.5日かけて、1行消すだけのあれだった・・・。
=> not need to call ngx_http_run_posted_requests

src/http/ngx_http_mruby_async.c, src/http/ngx_http_mruby_core.c, test/conf/nginx.conf
sub_requestの本文、ヘッダを取得するために、subrequestのbody filterで取っていたが、request構造体から取れることがわかったので書き直しました。
=> The return value of a subrequest can be retrieved immediately.

docs/test/README.md, test.sh
The purpose is to make valgrind available.
The environment variable `NGINX_RUNNER` allows for specifying the `nginx` launcher.
Also, the environment variable `NGINX_HEATTIME` allows for the time to wait for the test to run.
e.g.
```console
% NGINX_RUNNER=valgrind NGINX_HEATTIME=10 ./test.sh
```
:smile_cat: [ローカル環境で得られた、不穏なログを記録しておきました](https://gist.github.com/dearblue/26a18926bea9dca33ffce2a472da22e8)。
ログを全て確認したわけではありませんが、最初の40行までに報告された二つの問題は無視して大丈夫だと思います。
後の問題は・・・・・・僕は :see_no_evil: 目が :see_no_evil: 悪くて :see_no_evil: よく見えませんでした。
=> Allow `test.sh` to specify a launcher to start nginx

.github/workflows/test.yml, src/http/ngx_http_mruby_core.c, src/http/ngx_http_mruby_module.c
refs: https://github.com/matsumotory/ngx_mruby/pull/515
valgrindで検定されているメモリのエラーを修正します。
Nginx.redirectのループについてはコンフィグエラーなので、finalizeでケアしなくてもいいかなと思いました。
=> FIX some memory errors by valgrind

src/http/ngx_http_mruby_async.c
Hello!!
When repeatedly performing Nginx::Async.sleep, it overflows the value of MRB_ARY_LENGTH_MAX, resulting in the following error.
https://github.com/matsumotory/ngx_mruby/blob/af4228888587680d2c44b0aebbfb91e6e470d219/mruby/src/array.c#L26-L29
The issue also occurs with ngx_mruby v2.5.0.
There might be a misunderstanding on my part, or something missing. Please point out any discrepancies or omissions.
After looking into it, it appears that the error is occurring because mrb_gc_register is executed on every sleep operation. If mrb_gc_register is run at the start of the fiber and mrb_gc_unregister is run at the end of the fiber, the error will no longer occur.
I tried creating a PR. Please check it.
=> Improve fiber gc registration
