matsumotory/ngx_mruby

src/ngx_http_mruby_request.c
test/conf/nginx.conf
test/t/ngx_mruby.rb

Nginx::Request#sub_request? has compatibility between mod_mruby and ngx_mruby

Add Nginx::Request#sub_request?

---

src/ngx_http_mruby_request.c

sometimes missing string object, fixed #125.

Copy string object to nginx string

---

mrbgems/ngx_mruby_mrblib/mrblib/mrb_nginx.rb
mrbgems/rack-based-api/mrblib/rack.rb
src/ngx_http_mruby_core.c

based on https://github.com/matsumoto-r/mod_mruby/pull/67

Refactor Rack module for ngx_mruby

---

src/http/ngx_http_mruby_module.c
test/conf/nginx.conf
test/html/filter_dynamic_arg.rb
test/t/ngx_mruby.rb

`mruby_body_filte` create response data in handler finction same as `mruby_body_filter_code`.

Fix bug issue142

---

src/http/ngx_http_mruby_request.c
test/conf/nginx.conf
test/t/ngx_mruby.rb

Fix bug; pop array object when adding into headers

---

src/http/ngx_http_mruby_module.c
src/http/ngx_http_mruby_module.h
src/http/ngx_http_mruby_ssl.c
test/conf/nginx.conf
test/t/ngx_mruby.rb

```nginx
server {
listen       58083 ssl;
server_name  _;  
ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers         HIGH:!aNULL:!MD5;
ssl_certificate     __NGXDOCROOT__/dummy.crt;
ssl_certificate_key __NGXDOCROOT__/dummy.key;
mruby_ssl_handshake_handler_code '
ssl = Nginx::SSL.new
ssl.certificate_data = File.read "__NGXDOCROOT__/#{ssl.servername}.crt"
ssl.certificate_key_data = File.read "__NGXDOCROOT__/#{ssl.servername}.key"
';  
location / { 
mruby_content_handler_code "Nginx.rputs 'ssl test ok'";
}   
}
```

Add Nginx::SSL#{certificate_data=,certificate_key_data=}

---

AUTHORS
src/http/ngx_http_mruby_module.h

Bump up Version to v1.17.2

---

Makefile.in
build_config.rb
build_config_dynamic.rb

* Add default value for NUM_THREADS
* Use environment variable MRUBY_CONFIG instead	of copying build_config.rb

Minor build improvements.

---

src/http/ngx_http_mruby_ssl.c

GC protected at tls handshake hook for unexpeceted gc

---

src/http/ngx_http_mruby_module.c
src/stream/ngx_stream_mruby_module.c

Fix segmentation fault if code has a syntax error.

---

build_config.rb
src/http/ngx_http_mruby_module.c
src/http/ngx_http_mruby_module.h
src/http/ngx_http_mruby_ssl.c
src/http/ngx_http_mruby_upstream.c
src/http/ngx_http_mruby_var.c
test.sh

* Use nginx memory pool to avoid unexpected GC. Fixed #188
* Enable -DMRB_GC_STRESS for test

Fix unexpected GC

---

build.sh
build_config.rb
test.sh

* Fix incorrect nginx prefix
* Add missing -n to ln
* Don't clear cc.flags if NGX_MRUBY_CFLAGS environment variable is not defined. My fault.

Fix minor build bugs.

---

src/http/ngx_http_mruby_core.c

Don't need null termination for output chain

---

src/http/ngx_http_mruby_ssl.c

refs: https://twitter.com/minimum2scp/status/781102144149610496 https://gist.github.com/minimum2scp/b8f964aef8fdcff928296ca9849406b3#file-build-log-L2879-L2880

Fix openssl version compatibility

---

src/http/ngx_http_mruby_module.c

Fix typos in error message

---

src/http/ngx_http_mruby_module.c

Fix a typo

---

src/http/ngx_http_mruby_core.c

Introduce new internal function ngx_mrb_rputs_inner() to avoid code duplication.

refactoring ngx_mrb_rputs() and ngx_mrb_echo()

---

src/http/ngx_http_mruby_core.h
src/http/ngx_http_mruby_module.c
src/http/ngx_http_mruby_module.h
src/http/ngx_http_mruby_request.c
test/conf/nginx.conf
test/t/issue-268-test.rb
test/t/ngx_mruby.rb

Fix bug: issue-268 and add new directive for for read body

---

src/http/ngx_http_mruby_module.c
src/http/ngx_http_mruby_module.h
test/conf/nginx.conf

Rename `reqeust` with `request`

---

src/http/ngx_http_mruby_module.c

After upgrading to the latest ngx_mruby, I get a segmentation caused by unexpected GC as below.
The change fixes the problem.
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004ce08a in mrb_vm_exec (mrb=mrb@entry=0x86a6c0, proc=<optimized out>, pc=0x2)
at /home/vagrant/mon/ngx_mruby/mruby/src/vm.c:874
874	  INIT_DISPATCH {
Missing separate debuginfos, use: debuginfo-install glibc-2.17-106.el7_2.6.x86_64 libgcc-4.8.5-4.el7.x86_64 libstdc++-4.8.5-4.el7.x86_64 nss-softokn-freebl-3.16.2.3-13.el7_1.x86_64 openssl-libs-1.0.1e-51.el7_2.5.x86_64 pcre-8.32-15.el7_2.1.x86_64 zlib-1.2.7-15.el7.x86_64
(gdb) bt
#0  0x00000000004ce08a in mrb_vm_exec (mrb=mrb@entry=0x86a6c0, proc=<optimized out>, pc=0x2)
at /home/vagrant/mon/ngx_mruby/mruby/src/vm.c:874
#1  0x00000000004d5ee1 in …
```

Save code->proc from unexpected GC.

---

src/http/ngx_http_mruby_module.c
test.sh

* Extract methods to fix code duplication
* Remove dead code
* Remove semicolon duplication
* Cosmetic changes

Refactoring

---

mrbgems/auto-ssl/mrblib/mrb_auto_ssl.rb

refs https://letsencrypt.jp/usage/#SaveCertificate and https://github.com/matsumotory/ngx_mruby/blob/5609fc134a492a2913237e62b98baf3dce94089d/test/conf/auto-ssl/ngx_mruby-hook.sh#L37

use fullchain certificate on auto-ssl

---

.travis.yml

update test target nginx  from 1.13.0 to 1.13.1

---

AUTHORS

Could we add @yyamano and @pyama86 as authors?

Add @yyamano and @pyama86 as authors

---

docs/class_and_method/README.md

ドキュメント修正のみのためPRチェックリストは削除しました。

Correct errors in docs and add comments

---

docs/install/README.md

corrected documentation for dynamic module building

---

build_config.rb

Use brew openssl when compiling on darwin

---

src/http/ngx_http_mruby_module.c

- [x ] Add patches into `src/`.

Add missing mruby handler log for making my debugging life easier.

---

build.sh
test.sh

Fix typos about 'default'

---

src/http/ngx_http_mruby_module.c

PR #324  has same changing but we can not merge the PR until supporting 1.1.0 or later .
I send the PR for adding other directive which use hook in 1.0.2

Check supported version for each openssl API

---

src/http/ngx_http_mruby_module.c

Indicate which directive require the openssl version

---

docs/class_and_method/README.md
src/http/ngx_http_mruby_core.c
test/conf/nginx.conf
test/t/ngx_mruby.rb

Add Nginx.status_code= alias Nginx.return

---

src/http/ngx_http_mruby_async.c

fix: https://github.com/matsumotory/ngx_mruby/pull/355#discussion_r187798513

check valiable format

---

src/http/ngx_http_mruby_async.c

There was an error in log output

---

src/http/ngx_http_mruby_module.c

hi ryosuke-san.
refs: https://github.com/matsumotory/ngx_mruby/pull/360
fiberの処理結果を受け取るスタック変数の状態が不正になるため、ヒープ領域を確保するようにしました。これにより、不正な状態になることがなくなり、意図しない挙動をしなくなりました。

The result variable of fiber is secured with heep

---

src/http/ngx_http_mruby_async.c
src/http/ngx_http_mruby_async.h
src/http/ngx_http_mruby_connection.c
src/http/ngx_http_mruby_connection.h
src/http/ngx_http_mruby_core.c
src/http/ngx_http_mruby_core.h
src/http/ngx_http_mruby_filter.c
src/http/ngx_http_mruby_filter.h
src/http/ngx_http_mruby_init.c
src/http/ngx_http_mruby_init.h
src/http/ngx_http_mruby_module.c
src/http/ngx_http_mruby_module.h
src/http/ngx_http_mruby_request.c
src/http/ngx_http_mruby_request.h
src/http/ngx_http_mruby_server.c
src/http/ngx_http_mruby_server.h
src/http/ngx_http_mruby_ssl.c
src/http/ngx_http_mruby_ssl.h
src/http/ngx_http_mruby_upstream.c
src/http/ngx_http_mruby_upstream.h
src/http/ngx_http_mruby_var.c
src/http/ngx_http_mruby_var.h
src/stream/ngx_stream_mruby_connection.c
src/stream/ngx_stream_mruby_connection.h
src/stream/ngx_stream_mruby_core.c
src/stream/ngx_stream_mruby_core.h
src/stream/ngx_stream_mruby_init.c
src/stream/ngx_stream_mruby_init.h
src/stream/ngx_stream_mruby_module.c
src/stream/ngx_stream_mruby_module.h

This is non functional change.

Rafactor include files

---

docs/install/README.md

Fix link in document

---

src/http/ngx_http_mruby_upstream.c

Found it by inspection.  I'm sorry for no reproducible test code.

Lock peers and peer. Might be a problem with "zone".

---

src/http/ngx_http_mruby_async.c

In asynchronous processing,  `r->headers_out.status` may become NGX_OK in some cases, so I saved it explicitly.

Save the status before asynchronous processing

---

docs/DEVELOPMENT.md

I think not enough, but this is just a beginning. See #381
- [ x] Add docs into `docs/` if you change the features such as [build system](https://github.com/matsumotory/ngx_mruby/tree/master/docs/install), [Ruby methods, class](https://github.com/matsumotory/ngx_mruby/tree/master/docs/class_and_method) and [nginx directives](https://github.com/matsumotory/ngx_mruby/tree/master/docs/directives).

Initial version of developers document.

---

docs/DEVELOPMENT.md
update-devkit-subtree

Add ngx_devel_kit update tool and doc

---

TODO
docs/DEVELOPMENT.md
docs/install/README.md

This is just a documentation improvement includes:
* Remove TODO. It is not maintained.
* Add apply-clang-format to docs/DEVELOPMENT.md
* Make a significant improvement to docs/install/README.md
* Minor fixes.

Doc improvement

---

.gitignore
Vagrantfile
docs/DEVELOPMENT.md
misc/provision.sh

Support development environment using vagrant

---

docs/class_and_method/README.md
docs/directives/README.md

Doc only changes.
* Add missing mruby_upstream_keepalive directive to docs/directives/README.md.
* Massive changes of docs/class_and_method/README.md. 
Please use https://github.com/yyamano/ngx_mruby/blob/doc-improvement/docs/class_and_method/README.md for review.

Improve docs/class_and_method/README.md and docs/directives/README.md

---

build.sh
configure
configure.in

1. When I try to build it with on MAC I have got error that unknown option `-rpath=<openssl path>`. Seems like -rpath get updated.
2. Peoples might need to build it from specific openssl version. Especially, when you need use different openssl version for different project.

Linker error when build nginx module 

---

build.sh

Fix Mruby version upgrade issue #448

Mruby version upgrade require clean up properly (Issue #448)

---

docs/class_and_method/README.md

Fix typo in document

---

docs/install/README.md

Adjust install documentation.
- fix typo
- adjust header hierarchy

Adjust install documentation

---

test/t/ngx_mruby.rb

Fix typo in test

---

.gitignore

Ignore build_config.rb.lock generated by mruby build system.

---

docs/install/README.md

fix typo on doc/install/README.md

fix typo on doc/install/README.md

---

.github/workflows/test.yml

At first, I simply rewrote it to the actions format.

transformed travis test to github actions

---

build.sh
test.sh

Make it possible to build on FreeBSD
